### PR TITLE
Format and clean up README

### PR DESCRIPTION
**Pull request by achiurizo**
The initial README was a good start. This adds [some formatting and a screenshot](https://github.com/subspace/subspace-cli/blob/a1126d5f498a2de71c7837cd2fd285ecb0104662/README.md) to show-case the CLI a bit.

image

---

Follow up after merging this PR, we can add some other items such as:

- [ ] add link to Subspace Network
- [ ] add a shield badge for Subspace (like current network)
- [ ] do some re-organizing of existing commands (see [exa](https://github.com/ogham/exa) for some inspiration)

### CODE REVIEW

**Comment by ozgunozerk** [comment]
Is it a good idea to have `how to use` section both in the SS and in the readme?

**Comment by ozgunozerk** [comment]
@achiurizo thank you very much for handling the suggestions while I was asleep :)
I'm okay with all the changes, except one: I think `screen` is also a popular tool and I think we should keep the example instead of removing it. 

The format is much nicer though, thanks again!

**Review by ozgunozerk — DISMISSED** [review]
Thank you everyone for contributing to this @jfrank-summit @i1i1 @achiurizo

**Comment by ozgunozerk** [comment]
I put a meme to make readme more fun. If you think we should better not include it, feel free to remove it. I'm always trying to sprinkle some fun into our tech-heavy work to make our users smile :)

**Review by jfrank-summit — APPROVED** [review]
lgtm

**Review by i1i1 — APPROVED** [review]
Liked the meme. LGTM

**Comment by achiurizo** [comment]
> I put a meme to make readme more fun. If you think we should better not include it, feel free to remove it. I'm always trying to sprinkle some fun into our tech-heavy work to make our users smile :)

This is great! ✨ I love to see more kinds of expressions like this in projects. Let's continue to polish our format here and include visual elements and cleaner structures for our new CLI 😄

**Pull request merged**
