### PR TITLE
Add a New Feature Request template to the repo

### PR DESCRIPTION
**Pull request by stefanopepe**
First commit, testing the final result

### CODE REVIEW

**Comment by i1i1** [comment]
There is already an feature request template. Take a look at it: https://github.com/subspace/subspace-cli/blob/7b59b4714b401cd0d1b6c69d178c9b4193774dc3/.github/ISSUE_TEMPLATE/feature_request.yml

**Comment by ozgunozerk** [comment]
Yes, currently, when user submits an issue, they have 2 options:
- reporting a bug
- requesting a feature

**Comment by stefanopepe** [comment]
I'm totally aware, but I can't submit PRs for it :)

Let me extend yours here, and then we pick one of the two.

**Comment by ozgunozerk** [comment]
> I'm totally aware, but I can't submit PRs for it :)

hmm, i think you can. This way, it is hard to see the diff between the old/new version :/

**Comment by i1i1** [comment]
> GitHub UI doesn't allow me to edit the file here, I don't have access to repo settings. The only way is to manually edit the file locally (as I'm doing here), but I can only test it on another repo.
> 
> What if we merge this one and remove the old one? It was anyway created from an automated template, right?

Can you clone repo, manually edit old file and squash old commits though?

**Comment by stefanopepe** [comment]
Closing here, discussing at #167

**Pull request closed without merging**
